doc: add minutes for meeting 23 June
nodejs/TSC pull request #1045
Opened 2021-06-23 22:19 UTC by mhdawson

Signed-off-by: Michael Dawson <mdawson@devrus.com>

2021-06-23 22:50 UTC, Trott approved these changes
LGTM with recording link added (which will resolve the lint issue)

2021-06-24 04:32 UTC, gireeshpunathil approved these changes

2021-06-24 12:25 UTC, bl-ue requested changes

2021-06-24 12:25 UTC, bl-ue commented on meetings/2021-06-23.md
> +* **Recording**:
```suggestion
* **Recording**:
```

2021-06-24 20:08 UTC, mhdawson commented
@Trott who's uploading the video as I don't see it there yet.

2021-06-25 04:23 UTC, Trott commented
> @Trott who's uploading the video as I don't see it there yet.

/ping @mmarchini

2021-07-13 16:50 UTC, tniessen approved these changes

2021-07-16 18:26 UTC, mhdawson commented
@mmarchini are was there a recording that can be uploaded? If not we'll just land this as is.

2021-07-22 12:57 UTC, mhdawson commented
I checked today and I don't see a video on youtube. I'm going to land as is.

2021-07-22 12:57 UTC, merged