doc: add TSC vice chairperson
nodejs/TSC pull request #1219
Opened 2022-04-29 17:51 UTC by mhdawson

Add TSC vice chairperson as discussed in recent
meeting.

Signed-off-by: Michael Dawson <mdawson@devrus.com>

2022-04-29 17:52 UTC, mhdawson commented
@nodejs/TSC as discussed in the latest meeting and in https://github.com/nodejs/TSC/issues/1201

2022-04-29 18:06 UTC, gireeshpunathil approved these changes

2022-04-29 18:13 UTC, Trott commented on TSC-Charter.md
> +Chairperson to any other TSC member. Minutes or an
I don't think we need this change. It already says "Responsibility for directing individual meetings may be delegated by the TSC Chairperson to any other TSC member." So the TSC can choose to delegate a vice chair, and the chair can choose to delegate to the vice chair for any meeting they can't make. If we add the Vice Chair to the Charter, we're tying our hands that we always need to have a Vice Chair, even if we try this and find out it doesn't work.

2022-04-29 18:14 UTC, Trott requested changes
I don't think we need this change and I prefer keeping the Charter as non-specific as possible. If it's permitted by the Charter already (and I think it is), then we don't need to add it to the Charter.

2022-04-29 18:14 UTC, Trott commented
> I don't think we need this change and I prefer keeping the Charter as non-specific as possible. If it's permitted by the Charter already (and I think it is), then we don't need to add it to the Charter.

In other words, let's close this and just get right to the business of electing (or selecting) one or more Vice Chairs.

2022-04-29 18:58 UTC, mcollina approved these changes
lgtm

2022-05-02 20:29 UTC, mhdawson commented
Ok, if we don't need to document the vice-chair anywhere I'm happy to close.

2022-05-02 20:29 UTC, closed without merging